CREATE TABLE IF NOT EXISTS data (
id INT NULL,
uid INT NULL,
name VARCHAR(9) NULL,
age INT NULL,
gender VARCHAR(6) NULL,
type VARCHAR(7) NULL,
favorite_food VARCHAR(14) NULL,
img VARCHAR(59) NULL,
description VARCHAR(194) NULL,
date_create VARCHAR(5) NULL
);

INSERT INTO data VALUES
(2,11,'Roboid',4,'female','duck','Beets','http://via.placeholder.com/400/735/fff/?     text=Roboid','Enim ipsum minim velit adipisicing. Nisi sint irure consectetur aliqua.',NOW()),
(3,10,'Pyramis',8,'female','cow','Hay','http://via.placeholder.com/400/909/fff/?     text=Pyramis','Minim id ipsum cillum elit magna cillum ullamco qui. Culpa esse deserunt duis velit culpa et adipisicing.',NOW()),
(4,1,'Ecraze',10,'male','dog','Fish','http://via.placeholder.com/400/703/fff/?     text=Ecraze','Enim tempor ex ullamco qui ex velit proident ullamco sit ullamco sit labore irure magna. Tempor exercitation esse veniam dolore incididunt.',NOW()),
(5,10,'Radiantix',10,'female','sheep',' Clover','http://via.placeholder.com/400/747/fff/?     text=Radiantix','Aliqua non pariatur nostrud Lorem cillum duis. Ipsum ea enim voluptate magna cillum ut.',NOW()),
(6,7,'Geekfarm',10,'female','sheep','Balage','http://via.placeholder.com/400/936/fff/?     text=Geekfarm','Excepteur nisi amet tempor deserunt ullamco nulla et minim non sint tempor. Nulla ex pariatur nulla do.',NOW()),
(7,1,'Uncorp',7,'male','donkey','Sweet Poteto','http://via.placeholder.com/400/905/fff/?     text=Uncorp','Veniam culpa sunt laboris dolor tempor consequat magna nisi tempor eu mollit. Dolor consequat ad quis duis Lorem.',NOW()),
(8,4,'Vidto',4,'male','pig','pumpkins','http://via.placeholder.com/400/757/fff/?     text=Vidto','Commodo irure excepteur est ut sit culpa officia consectetur ex pariatur duis excepteur ex. Duis pariatur irure eu minim esse veniam aliquip nostrud mollit laborum eiusmod labore nulla sint.',NOW()),
(9,10,'Zogak',5,'female','cow',' Barley','http://via.placeholder.com/400/723/fff/?     text=Zogak','Veniam ipsum nisi excepteur esse exercitation esse nisi ut dolore eiusmod ut aliquip est. Aute consequat fugiat dolore nulla ipsum non incididunt.',NOW()),
(10,11,'Norsul',1,'male','chicken','Cottage Cheese','http://via.placeholder.com/400/911/fff/?     text=Norsul','Nisi irure anim tempor duis. Aliquip enim minim officia consequat eu esse aliquip non consequat laborum.',NOW()),
(11,6,'Xerex',2,'male','sheep','Balage','http://via.placeholder.com/400/966/fff/?     text=Xerex','Adipisicing velit aliquip duis esse cupidatat eiusmod. Excepteur quis in id nostrud ex est non veniam tempor nisi.',NOW()),
(12,3,'Kindaloo',8,'male','cow','Silage','http://via.placeholder.com/400/780/fff/?     text=Kindaloo','Veniam ut ex commodo culpa dolore minim minim dolore excepteur esse aliquip laboris duis. Aute et proident commodo officia labore sit Lorem adipisicing aliqua irure ipsum anim pariatur proident.',NOW()),
(13,3,'Portica',10,'male','pig','Cucumbers','http://via.placeholder.com/400/893/fff/?     text=Portica','Eu exercitation sit ut labore Lorem incididunt sint est minim. Mollit tempor quis id culpa nisi aliquip qui.',NOW()),
(14,2,'Uniworld',1,'female','pig','Cucumbers','http://via.placeholder.com/400/925/fff/?     text=Uniworld','Nulla pariatur officia elit ullamco commodo nulla sunt voluptate laboris fugiat duis. Nulla qui est ut esse excepteur in nulla voluptate commodo qui ea adipisicing ullamco incididunt.',NOW()),
(15,7,'Gushkool',6,'male','dog','Peanuts Butter','http://via.placeholder.com/400/969/fff/?     text=Gushkool','Eu ea sint veniam sunt elit reprehenderit dolore amet id consequat tempor veniam Lorem. Consectetur sit fugiat minim tempor elit culpa eu voluptate nostrud proident ad est anim.',NOW()),
(16,4,'Fleetmix',1,'female','pig','pumpkins','http://via.placeholder.com/400/999/fff/?     text=Fleetmix','Proident do culpa ex Lorem et anim esse mollit aute dolore. Laboris sit duis velit sit cillum id laboris nisi tempor eiusmod.',NOW()),
(17,7,'Bristo',8,'female','duck','Turnips','http://via.placeholder.com/400/923/fff/?     text=Bristo','Tempor officia ut aliquip enim non cillum anim consequat anim ex excepteur anim non Lorem. Pariatur quis dolor est elit cupidatat nulla proident id aute nisi.',NOW()),
(18,11,'Sonique',9,'female','horse','Cantaloupe','http://via.placeholder.com/400/929/fff/?     text=Sonique','Lorem minim in Lorem minim ipsum aliquip eiusmod cillum consequat fugiat laborum. Dolore ut mollit eu irure aliqua deserunt qui.',NOW()),
(19,8,'Tetak',2,'male','cow',' Barley','http://via.placeholder.com/400/835/fff/?     text=Tetak','Pariatur non est aute dolore culpa voluptate amet. Consectetur tempor id dolor magna nulla enim veniam aute nisi eu ea.',NOW()),
(20,4,'Tsunamia',6,'male','donkey','Turnips','http://via.placeholder.com/400/789/fff/?     text=Tsunamia','Esse cillum proident quis laboris nostrud deserunt mollit aute. Ex enim nostrud nulla laborum esse esse ad exercitation cupidatat nulla in veniam anim labore.',NOW()),
(21,4,'Stelaecor',8,'female','cow','Hay','http://via.placeholder.com/400/846/fff/?     text=Stelaecor','Laboris adipisicing aliqua nisi labore duis. Cupidatat reprehenderit velit voluptate Lorem qui et qui Lorem.',NOW()),
(22,7,'Quailcom',4,'male','donkey','Hay','http://via.placeholder.com/400/799/fff/?     text=Quailcom','Sunt excepteur laborum incididunt voluptate enim culpa labore do aliquip duis magna sunt. Irure dolor incididunt in magna dolore sit veniam.',NOW()),
(23,5,'Yurture',6,'female','dog','Cheese','http://via.placeholder.com/400/850/fff/?     text=Yurture','Ad non dolor incididunt mollit irure elit ea deserunt aliquip. Sint enim amet fugiat tempor elit ut sint cupidatat cupidatat ad dolore.',NOW()),
(24,5,'Futuris',3,'male','pig','Cucumbers','http://via.placeholder.com/400/732/fff/?     text=Futuris','Nostrud commodo duis cupidatat voluptate tempor irure ex ad adipisicing irure esse ut veniam. Eu excepteur ex exercitation deserunt aliqua dolore.',NOW()),
(25,3,'Waab',2,'female','chicken','Cottage Cheese','http://via.placeholder.com/400/872/fff/?     text=Waab','Commodo officia ut aliqua nostrud nisi. Id et eu tempor veniam eiusmod sunt ut id duis occaecat do consectetur excepteur.',NOW()),
(26,11,'Comtrek',9,'female','pig','Cucumbers','http://via.placeholder.com/400/936/fff/?     text=Comtrek','Labore cillum ad reprehenderit aliquip anim amet tempor id sint veniam. Aliqua quis nulla ea amet.',NOW());